#!/bin/bash
set -e
#DEBHELPER#
. /usr/share/debhelper/dh_installdeb
dh_systemd_enable --user
systemctl --user daemon-reload
systemctl --user enable dad-joke.timer --now
systemctl --user start dad-joke.service || true
exit 0
