name: Build DEB Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y devscripts debhelper

    - name: Build DEB package
      run: debuild -us -uc

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dad-joke-deb
        path: ../*.deb
